// CustBasicRptImages.pkg - images for CustomerListBR.rv
// Since report images, such as the one used here, are not fully supported by
// the Studio, we have placed the images for this report in a separate package.

/CustHdr
                             Customer Listing                      Page:___.
Number  Name
----------------------------------------------------------------------------
/CustBody
_____.  ______________________________
/Footer

Date printed:  __/__/____
/*