# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9be621e3858c8ad63a657136115a5b7c53f1d4864cfd41104f0c748b4b444303a69dd895cea81bc4fba6c8c5d36a5f3de68a7f8a379dfd26c51da69709892680

test:
  secret_key_base: a747e8c232efa9b1a181febecf8bd70a4952aa7325cf06a49b2ca594f18f90b2a117edf44aa8a8dea5a822e13dfda277793a47ba9f0b4a339a3db8010d4f4f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
